version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    restart: unless-stopped
    networks: 
      - internalnetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - auth
      - chat

  auth:
    build: ./auth
    container_name: auth
    networks:
      - internalnetwork

  chat:
    build: ./chat
    container_name: chat
    networks:
      - internalnetwork
networks:
  internalnetwork:
    driver: bridge