name: Deploy to Server

on:
  workflow_dispatch:

env:
  SERVER_USER: root
  DEPLOY_PATH: /opt/demoapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            docker compose --env-file .env -f docker-compose-deploy.yml pull
            docker compose --env-file .env -f docker-compose-deploy.yml up -d --remove-orphans


# This is for use when you want to deploy to a server from GitHub Actions. Refer to readme to use 
# the compose file directly in your computer.